version: "3.8"

services:
  api:
    image: node:15.10
    command: sh -c "npm install && dev start"
    networks:
      - hm
    ports:
      - 5000:5000
    links:
      - postgres
    depends_on:
      - postgres
    working_dir: /hm
    volumes:
      - type: bind
        source: ./
        target: /hm
  client:
    image: node:15.10
    command: sh -c "npm install && npm start"
    networks:
      - hm
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    links:
      - api
    working_dir: /hm/client
    volumes:
      - type: bind
        source: ./client
        target: /hm/client
  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - hm
    links: 
      - postgres
    depends_on:
      - postgres
    ports:
      - 8080:80
    logging: 
      driver: none
    environment: 
      - PGADMIN_DEFAULT_EMAIL=dogan.hurkan@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
  postgres:
    image: postgres:13.2-alpine
    networks:
      - hm
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
volumes:
  pg-data:
networks:
  hm:
