version: "3.8"

services:
  api:
    image: node:15.10
    command: sh -c "npm install && npm start"
    ports:
      - 5000:5000
    links:
      - mysql
    depends_on:
      - mysql
    working_dir: /hm
    volumes:
      - type: bind
        source: ./
        target: /hm
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DB=hugos
  client:
    image: node:15.10
    command: sh -c "npm install && npm start"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    links:
      - api
    working_dir: /hm/client
    volumes:
      - type: bind
        source: ./client
        target: /hm/client
  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:8080
  mysql:
    image: mysql:5.7
    volumes:
      - hm-app-mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=hugos

volumes:
  hm-app-mysql-data:
